version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: ""
    commit-message:
      prefix: "Git submodule"
    labels:
      - "dependencies"
